document.write("<table border=0 width=780 cellpadding=0 cellspacing=0 align=center>");
document.write("	<tr>");
document.write("		<td height=100><a href=index.html><IMG SRC=images/logo.gif WIDTH=273 HEIGHT=58 BORDER=0 ALT= vivah4u.com></a></td>");
document.write("		<td align=right>");
document.write("			<!--MEMBER TABLE STARTS HERE-->");
document.write("			<table border=0 width=440 cellpadding=0 cellspacing=0 background=images/login-bg.gif>");
document.write("				<tr>");
document.write("					<td width=11><IMG SRC=images/login-left.gif WIDTH=12 HEIGHT=67 BORDER=0 ALT=></td>");
document.write("					<td width=418 align=cetner>");
document.write("						<table border=0 cellpadding=2 cellspacing=2>");
document.write("						document.write("							<tr>");
document.write("								<td class=orange-text><B>MEMBERS LOGIN</B></td>");
document.write("								<td><input type=text name=login value=ID/ E-mail size=15 class=black-text></td>");
document.write("								<td><input type=password name=password value=password size=15 class=black-text></td>");
document.write("								<td><input type=image SRC=images/button-go.gif WIDTH=40 HEIGHT=20 BORDER=0 ALT=></td>");
document.write("							</tr>");
document.write("							<tr>");
document.write("								<td align=right colspan=2><A HREF=registration.html>free registration</A>&nbsp;|</td>");
document.write("								<td align=left colspan=2><A HREF=forgotpassword.html>forgot your password</A></td>");
document.write("							</tr>");
document.write("						</table>");
document.write("					</td>");
document.write("					<td width=11 align=right><IMG SRC=images/login-right.gif WIDTH=15 HEIGHT=67 BORDER=0 ALT=></td>");
document.write("				</tr>");
document.write("			</table>");
document.write("			<!--MEMBER TABLE ENDS HERE-->");
document.write("		</td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("		<td colspan=2 align=right>");
document.write("			<!--TOP LINKS TABLE STARTS HERE-->");
document.write("			<table border=0 cellpadding=0 cellspacing=0 background=images/linn-bg.gif>");
document.write("				<tr>");
document.write("					<td><IMG SRC=images/link-left.gif WIDTH=15 HEIGHT=22 BORDER=0 ALT=></td>");
document.write("					<td><A HREF=/V4U/member_profile.aspx class=white-link>My vivah4you</A></td>");
document.write("					<td><IMG SRC=images/link-middle.gif WIDTH=36 HEIGHT=22 BORDER=0 ALT=></td>");
document.write("					<td><A HREF=memberships.aspx class=white-link>Memberships</A></td>");
document.write("					<td><IMG SRC=images/link-middle.gif WIDTH=36 HEIGHT=22 BORDER=0 ALT=></td>");
document.write("					<td><A HREF=/V4U/Master/ViewSuccessStory.aspx class=white-link>Success Stories</A></td>");
document.write("					<td><IMG SRC=images/link-middle.gif WIDTH=36 HEIGHT=22 BORDER=0 ALT=></td>");
document.write("					<td><A HREF=gift_shops.html class=white-link>Gift shops</A></td>");
document.write("					<td><IMG SRC=images/link-right.gif WIDTH=12 HEIGHT=22 BORDER=0 ALT=></td>");
document.write("				</tr>");
document.write("			</table>");
document.write("			<!--TOP LINKS TABLE ENDS HERE-->");
document.write("		</td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("		<td colspan=2><IMG SRC=images/link-bottom.gif WIDTH=780 HEIGHT=8 BORDER=0 ALT=></td>");
document.write("	</tr>");
document.write("</table>");