document.write("<table border=0 width=780 cellpadding=0 cellspacing=0 align=center>");
document.write("	<tr>");
document.write("		<td height=100><a href=/V4U/default.aspx><IMG SRC=/V4U/images/logo.gif WIDTH=273 HEIGHT=58 BORDER=0 ALT= hspace=10></a></td>");
document.write("		<td align=right valign=bottom><a href=/V4U/logout.aspx class=logoutLink>Logout</a>&nbsp;&nbsp;&nbsp; New Messages(0)<br><br>");

document.write("		</td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("		<td colspan=2 align=right>");
document.write("			<!--TOP LINKS TABLE STARTS HERE-->");
document.write("			<table border=0 cellpadding=0 cellspacing=0 background=/V4U/images/linn-bg.gif>");
document.write("				<tr>");
document.write("					<td><IMG SRC=/V4U/images/link-left.gif WIDTH=15 HEIGHT=22 BORDER=0 ALT=></td>");
document.write("					<td><A HREF=/V4U/member_profile.aspx class=white-link>My vivah4you</A></td>");
document.write("					<td><IMG SRC=/V4U/images/link-middle.gif WIDTH=36 HEIGHT=22 BORDER=0 ALT=></td>");
document.write("					<td><A HREF=/V4U/memberships.aspx class=white-link>Memberships</A></td>");
document.write("					<td><IMG SRC=/V4U/images/link-middle.gif WIDTH=36 HEIGHT=22 BORDER=0 ALT=></td>");
document.write("					<td><A HREF=/V4U/Master/ViewSuccessStory.aspx class=white-link>Success Stories</A></td>");
document.write("					<td><IMG SRC=/V4U/images/link-middle.gif WIDTH=36 HEIGHT=22 BORDER=0 ALT=></td>");
document.write("					<td><A HREF=# class=white-link>Gift shops</A></td>");
document.write("					<td><IMG SRC=/V4U/images/link-right.gif WIDTH=12 HEIGHT=22 BORDER=0 ALT=></td>");
document.write("				</tr>");
document.write("			</table>");
document.write("			<!--TOP LINKS TABLE ENDS HERE-->");
document.write("		</td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("		<td colspan=2><IMG SRC=/V4U/images/link-bottom.gif WIDTH=780 HEIGHT=8 BORDER=0 ALT=></td>");
document.write("	</tr>");
document.write("</table>");