document.write("<table width=218 cellpadding=0 cellspacing=0 border=0 class=liteyellow_bg>");
//document.write("<tr><td align=left style='padding-left:10px;padding-bottom:10px'><b>Welcome " + '<%=Session("proid")%>' + "</b></td></tr>");
document.write("<tr><td align=center><img src=/V4U/images/myvivah_heading.gif></td></tr>");
document.write("	<tr>");
document.write("	<td align=center>");
document.write("<table border=0 cellspacing=0 cellpadding=0 id=myVivah width=212>");
document.write("<tr><td>")
	document.write("<table border=0 cellspacing=0 cellpadding=0  width=100% id=leftProfile>");
	document.write("<tr><td><img src=/V4U/images/downArrow.gif width=6 height=4 hspace=5><b>My Profile</b></td></tr>");
	document.write("<tr><td class=leftPadding20><img src=/V4U/images/rightblackarrow.gif width=4 height=6 hspace=5><a href=/V4U/member_profile.aspx class=leftSubLinks>Manage Profile</a></td></tr>");
	document.write("<tr><td class=leftPadding20><img src=/V4U/images/rightblackarrow.gif width=4 height=6 hspace=5><a href=/V4U/Edit/edit_profile_preferred.aspx class=leftSubLinks>Edit Preffered Partner Profile</a></td></tr>");
	document.write("<tr><td class=leftPadding20><img src=/V4U/images/rightblackarrow.gif width=4 height=6 hspace=5><a HREF=/V4U/UploadPhotoNVideos.aspx class=leftSubLinks>Manage Photo/ Video</a></td></tr>");
	document.write("<tr><td class=leftPadding20><img src=/V4U/images/rightblackarrow.gif width=4 height=6 hspace=5><a href=/V4U/Search/BrowseProfile.aspx class=leftSubLinks>Browse Profiles</a></td></tr>");
	document.write("<tr><td class=leftPadding20><img src=/V4U/images/rightblackarrow.gif width=4 height=6 hspace=5><a href=changepassowrd.html class=leftSubLinks>Change Password</a></td></tr>");
	document.write("<tr><td class=borderTop><img src=/V4U/images/downArrow.gif width=6 height=4 hspace=5><b>Personal Mailbox</b></td></tr>");
	document.write("<tr><td class=leftPadding20><img src=/V4U/images/rightblackarrow.gif width=4 height=6 hspace=5><a href=/V4U/Communication/InBox.aspx class=leftSubLinks>Inbox</a></td></tr>");
//	document.write("<tr><td class=leftPadding20><img src=/images/rightblackarrow.gif width=4 height=6 hspace=5><a href=# class=leftSubLinks>Alerts</a></td></tr>");
	document.write("<tr><td class=leftPadding20><img src=/V4U/images/rightblackarrow.gif width=4 height=6 hspace=5><a href=/V4U/Communication/reply_mail.aspx class=leftSubLinks>Compose</a></td></tr>");
	document.write("<tr><td  class=borderTop><img src=/V4U/images/downArrow.gif width=6 height=4 hspace=5><a href=# class=leftLinks>Security & Privacy</a></td></tr>");
	document.write("<tr><td class=leftPadding20><img src=/V4U/images/rightblackarrow.gif width=4 height=6 hspace=5><a href=sp_for_profile.html class=leftSubLinks>Profile Settings</a></td></tr>");

	document.write("<tr><td class=leftPadding20><img src=/V4U/images/rightblackarrow.gif width=4 height=6 hspace=5><a href=sp_block_member.html class=leftSubLinks>Block a Member</a></td></tr>");
	document.write("<tr><td class=leftPadding20><img src=/V4U/images/rightblackarrow.gif width=4 height=6 hspace=5><a href=myalerts.html class=leftSubLinks>My Alerts</a></td></tr>");
	document.write("<tr><td  class=borderTop><img src=/V4U/images/rightorangearrow.gif width=4 height=6 hspace=5><a href=whos_online.html class=leftLinks>Who's Online</a></td></tr>");
	document.write("<tr><td  class=borderTop><img src=/V4U/images/rightorangearrow.gif width=4 height=6 hspace=5><a href=reportabuse.html class=leftLinks>Report Abuse</a></td></tr>");
	document.write("<tr><td  class=borderTop><img src=/V4U/images/rightorangearrow.gif width=4 height=6 hspace=5><a href=my_saved_search.html class=leftLinks>My Saved Searches</a></td></tr>");
	document.write("<tr><td  class=borderTop><img src=/V4U/images/rightorangearrow.gif width=4 height=6 hspace=5><a href=statistics.html class=leftLinks>Statistics</a></td></tr>");
	document.write("</table>");
document.write("</td></tr>");
document.write("</table>");
document.write("</td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("	<td valign=top align=center><br><img src=/V4U/images/advance_search_header.gif ></td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("	<td align=center>");
document.write("<table width=212 cellpadding=2 cellspacing=0 border=0 id=leftSearch>");
document.write("<tr><td colspan=4><img src=/images/spacer.gif width=1 height=3></td></tr>");
document.write("<tr>");
document.write("					<td width=44% align=right nowrap class=black-text valign=top>Looking for</td>");
document.write("					<td width=56% align=left class=black-text nowrap>");
document.write("					<select class=black-text style=width:100px;>");
document.write("						<option>Bride</option>");
document.write("						<option>Groom</option>");
document.write("					</select>");
document.write("					</td>");
document.write("				</tr>");
document.write("				<tr>");
document.write("						<td class=black-text align=right>with photo</td>");
document.write("						<td><input type=checkbox></td>");
document.write("				</tr>");
document.write("				<tr>");
document.write("					<td align=right class=black-text>of Age</td>");
document.write("					<td align=left class=black-text>");
document.write("					<select class=black-text style=width:40px;>");
document.write("						<option>18</option>");
document.write("						<option>19</option>");
document.write("						<option>20</option>");
document.write("					</select>");
document.write("					to");
document.write("					<select class=black-text style=width:40px;>");
document.write("						<option>18</option>");
document.write("						<option>19</option>");
document.write("						<option>20</option>");
document.write("						<option>21</option>");
document.write("						<option>22</option>");
document.write("						<option>23</option>");
document.write("						<option>24</option>");
document.write("						<option>25</option>");
document.write("					</select>");
document.write("					</td>");
document.write("				</tr>");
document.write("				<tr>");
document.write("						<td class=black-text align=right>of Community</td>");
document.write("						<td class=black-text>");
document.write("						<select class=black-text style=width:100px;>");
document.write("						<option>Assamese</option>");
document.write("						<option>Bengali</option>");
document.write("						<option>Gujarati</option>");
document.write("						<option>Hindi</option>");
document.write("						<option>Kannada</option>");
document.write("						<option>Malayalee</option>");
document.write("						<option>Marathi</option>");
document.write("					</select>");
document.write("						</td>");
document.write("				</tr>");
document.write("				<tr>");
document.write("						<td class=black-text align=right>of Country</td>");
document.write("						<td class=black-text>");
document.write("						<select class=black-text style=width:100px;>");
document.write("							<option>India</option>");
document.write("							<option>Pakistan</option>");
document.write("							<option>UK</option>");
document.write("						</select>");
document.write("						</td>");
document.write("				</tr>");
document.write("<tr><td></td><td colspan=3><a href=search_result.html><img src=/V4U/images/top_search_btn.gif border=0></a></td></tr>");
document.write("<tr>");
document.write("<td></td><td colspan=3 class=black_text_small valign=top><a class=black_text_small href=/V4U/Search/advance_search.aspx>Advanced Search</a><br></td>");
document.write("</tr>");
document.write("<tr><td colspan=4><img src=/V4U/images/spacer.gif width=1 height=3></td></tr>");
document.write("</table><br>");


document.write("	</td></tr>");
document.write("	<!--tr>");
document.write("	<td valign=top align=center><img src=/images/banner_couple.jpg width=194 height=303></td>");
document.write("	</tr-->");
document.write("	<tr>");
document.write("	<td valign=top><img src=/images/spacer.gif width=1 height=9></td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("		<td valign=top class=success_stories align=center>");
document.write("		<!--start for text-->");
document.write("		<table width=80% cellpadding=4 cellspacing=4 border=0>");
document.write("		<tr>");
document.write("			<td class=orange-text><b>Success Story</b></td>");
document.write("		</tr>");
document.write("		<tr>");
document.write("			<td height=110>&nbsp;</td>");
document.write("		</tr>");
document.write("		<tr>");
document.write("			<td align=right><a class=black-text href=#><u>Read Success Stories</u></a></td>");
document.write("		</tr>");
document.write("		</table>");
document.write("		<!--end for text-->");
document.write("		</td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("		<td valign=top><img src=/images/spacer.gif width=1 height=10></td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("		<td class=gift_shops align=center valign=top>");
document.write("		<!--start for text-->");
document.write("		<table width=90% cellpadding=0 cellspacing=0 border=0>");
document.write("		<tr>");
document.write("			<td valign=top><img src=/images/spacer.gif width=1 height=9></td>");
document.write("		</tr>");
document.write("		<tr>");
document.write("			<td class=drk_green_text align=left><b>Gift Shops</b></td>");
document.write("		</tr>");
document.write("		<tr>");
document.write("			<td valign=top><img src=/images/spacer.gif width=1 height=12></td>");
document.write("		</tr>");
document.write("		<tr>");
document.write("			<td class=pad_lftrite><p align=justify><span class=black-text>About my nature i am a calm type person but sometimes</span></p></td>");
document.write("		</tr>");
document.write("		<tr>");
document.write("			<td valign=top><img src=/images/spacer.gif width=1 height=5></td>");
document.write("		</tr>");
document.write("		<tr>");
document.write("			<td class=pad_lftrite nowrap><a href=gift_shops.html><u>read more.</u></a></td>");
document.write("		</tr>");
document.write("		</table>");
document.write("		<!--end for text-->");
document.write("		</td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("		<td valign=top>&nbsp;</td>");
document.write("	</tr>");
document.write("</table>");