document.write("<table width=218 cellpadding=0 cellspacing=0 border=0 class=liteyellow_bg>");
document.write("	<tr>");
document.write("	<td align=center><a href=/V4U/Registration.aspx><img src=/V4U/images/register_free_banner.gif width=172 height=86 border=0></a></td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("	<td valign=top align=center><br><img src=/V4U/images/advance_search_header.gif width=212 height=31></td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("	<td align=center>");


document.write("<table width=212 cellpadding=2 cellspacing=0 border=0 id=leftSearch>");
document.write("<tr><td colspan=4><img src=images/spacer.gif width=1 height=3></td></tr>");
document.write("<tr>");
document.write("					<td width=44% align=right nowrap class=black-text valign=top>Looking for</td>");
document.write("					<td width=56% align=left class=black-text nowrap>");
document.write("					<select class=black-text id=cboFor name=cboFor style=width:100px;>");
document.write("						<option value=Female>Bride</option>");
document.write("						<option value=Male>Groom</option>");
document.write("					</select>");
document.write("					</td>");
document.write("				</tr>");
document.write("				<tr>");
document.write("						<td class=black-text align=right>with photo</td>");
document.write("						<td><input id=chkphoto name=chkphoto type=checkbox></td>");
document.write("				</tr>");
document.write("				<tr>");
document.write("					<td align=right class=black-text>of Age</td>");
document.write("					<td align=left class=black-text>");
document.write("					<select class=black-text style=width:40px;>");
document.write("						<option>18</option>");
document.write("						<option>19</option>");
document.write("						<option>20</option>");
document.write("					</select>");
document.write("					to");
document.write("					<select class=black-text style=width:40px;>");
document.write("						<option>18</option>");
document.write("						<option>19</option>");
document.write("						<option>20</option>");
document.write("						<option>21</option>");
document.write("						<option>22</option>");
document.write("						<option>23</option>");
document.write("						<option>24</option>");
document.write("						<option>25</option>");
document.write("					</select>");
document.write("					</td>");
document.write("				</tr>");
document.write("				<tr>");
document.write("						<td class=black-text align=right>of Community</td>");
document.write("						<td class=black-text>");
document.write("						<select class=black-text style=width:100px;>");
document.write("						<option>Assamese</option>");
document.write("						<option>Bengali</option>");
document.write("						<option>Gujarati</option>");
document.write("						<option>Hindi</option>");
document.write("						<option>Kannada</option>");
document.write("						<option>Malayalee</option>");
document.write("						<option>Marathi</option>");
document.write("					</select>");
document.write("						</td>");
document.write("				</tr>");
document.write("				<tr>");
document.write("						<td class=black-text align=right>of Country</td>");
document.write("						<td class=black-text>");
document.write("						<select class=black-text style=width:100px;>");
document.write("							<option>India</option>");
document.write("							<option>Pakistan</option>");
document.write("							<option>UK</option>");
document.write("						</select>");
document.write("						</td>");
document.write("				</tr>");
document.write("<tr><td></td><td colspan=3><a href=#><img src=/V4U/images/top_search_btn.gif border=0></a></td></tr>");
document.write("<tr>");
document.write("<td></td><td colspan=3 class=black_text_small valign=top><a class=black_text_small href=/V4U/Search/advance_search.aspx>Advanced Search</a><br></td>");
document.write("</tr>");
document.write("<tr><td colspan=4><img src=/V4U/images/spacer.gif width=1 height=3></td></tr>");
document.write("</table><br>");


document.write("	</td></tr>");
document.write("	<!--tr>");
document.write("	<td valign=top align=center><img src=/V4U/images/banner_couple.jpg width=194 height=303></td>");
document.write("	</tr-->");
document.write("	<tr>");
document.write("	<td valign=top><img src=images/spacer.gif width=1 height=9></td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("		<td valign=top class=success_stories align=center>");
document.write("		<!--start for text-->");
document.write("		<table width=80% cellpadding=4 cellspacing=4 border=0>");
document.write("		<tr>");
document.write("			<td class=orange-text><b>Success Story</b></td>");
document.write("		</tr>");
document.write("		<tr>");
document.write("			<td height=110>&nbsp;</td>");
document.write("		</tr>");
document.write("		<tr>");
document.write("			<td align=right><a class=black-text href=#><u>Read Success Stories</u></a></td>");
document.write("		</tr>");
document.write("		</table>");
document.write("		<!--end for text-->");
document.write("		</td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("		<td valign=top><img src=images/spacer.gif width=1 height=10></td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("		<td class=gift_shops align=center valign=top>");
document.write("		<!--start for text-->");
document.write("		<table width=90% cellpadding=0 cellspacing=0 border=0>");
document.write("		<tr>");
document.write("			<td valign=top><img src=images/spacer.gif width=1 height=9></td>");
document.write("		</tr>");
document.write("		<tr>");
document.write("			<td class=drk_green_text align=left><b>Gift Shops</b></td>");
document.write("		</tr>");
document.write("		<tr>");
document.write("			<td valign=top><img src=images/spacer.gif width=1 height=12></td>");
document.write("		</tr>");
document.write("		<tr>");
document.write("			<td class=pad_lftrite><p align=justify><span class=black-text>About my nature i am a calm type person but sometimes..</span></p></td>");
document.write("		</tr>");
document.write("		<tr>");
document.write("			<td valign=top><img src=images/spacer.gif width=1 height=5></td>");
document.write("		</tr>");
document.write("		<tr>");
document.write("			<td class=pad_lftrite nowrap><a href=#><u>read more...</u></a></td>");
document.write("		</tr>");
document.write("		</table>");
document.write("		<!--end for text-->");
document.write("		</td>");
document.write("	</tr>");
document.write("	<tr>");
document.write("		<td valign=top>&nbsp;</td>");
document.write("	</tr>");
document.write("</table>");