//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace AngularJsCrudOperations
{
    public partial class EmployeeData
    {
        [Required(ErrorMessage = "Id is required")]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is required", AllowEmptyStrings = false)]
        public string Name { get; set; }

        [Required(ErrorMessage = "Father Name Is required", AllowEmptyStrings = false)]
        public string FatherName { get; set; }

        [Required(ErrorMessage = "Email Id is required", AllowEmptyStrings = false)]
        public string EmailID { get; set; }

        [Required(ErrorMessage = "Phone Number is required", AllowEmptyStrings = false)]
        public string PhoneNo { get; set; }

        [Required(ErrorMessage = "Address is required", AllowEmptyStrings = false)]
        public string Address { get; set; }
    }
}
