using System;

namespace HiveReport.WebAdmin.Infrastructure.Sql.Exceptions
{
    [Serializable]
    class GetIdentitySqlException : Exception
    {
        public GetIdentitySqlException()
            : base("Error to Get the last ID generated by the DB")
        {
        }

        public GetIdentitySqlException(string NameId)
            : base($"Error to Get the last {NameId} generated by the DB")
        {
        }
    }
}
